<?php
$claseCuerpo = 'layout-fixed sidebar-expand-lg bg-body-tertiary dashboard-intesis';
require $configuracion->raiz() . '/src/Vistas/plantillas/encabezado.php';
$appNombre = $configuracion->obtener('APP_NOMBRE', 'INTESIS');
$appUrl = rtrim($configuracion->obtener('APP_URL', ''), '/');
?>
<div class="app-wrapper">
    <nav class="app-header navbar navbar-expand navbar-intesis"><div class="container-fluid"><ul class="navbar-nav"><li class="nav-item"><button class="nav-link btn btn-link" data-lte-toggle="sidebar" type="button"><i class="bi bi-list"></i></button></li><li class="nav-item"><span class="nav-link breadcrumb-navbar"><span><?= htmlspecialchars($appNombre) ?></span><i class="bi bi-chevron-right"></i><span>Inventario</span><i class="bi bi-chevron-right"></i><strong>Marcas</strong></span></li></ul><ul class="navbar-nav ms-auto align-items-center"><li class="nav-item me-3 d-none d-md-block"><span class="usuario-navbar"><?= htmlspecialchars((($usuario['bodega'] ?? null) ? $usuario['bodega'] . ' - ' : '') . $usuario['nombre']) ?></span></li><li class="nav-item"><form action="<?= $appUrl ?>/salir" method="post"><button class="btn btn-salir" type="submit" title="Cerrar sesion"><i class="bi bi-power"></i></button></form></li></ul></div></nav>
    <aside class="app-sidebar sidebar-intesis" data-bs-theme="dark"><div class="sidebar-brand"><a href="<?= $appUrl ?>/dashboard" class="brand-link"><span class="brand-icon"><i class="bi bi-grid-1x2-fill"></i></span><span class="brand-text"><?= htmlspecialchars($appNombre) ?></span></a></div><div class="sidebar-wrapper"><?php require $configuracion->raiz() . '/src/Vistas/plantillas/menu_lateral.php'; ?></div></aside>
    <main class="app-main"><div class="app-content"><div class="container-fluid"><section class="panel-crud">
        <?php if ($permisos['crear']): ?><div class="panel-crud-cabecera"><button type="button" class="btn btn-intesis btn-crud" data-bs-toggle="modal" data-bs-target="#modalMarca" data-modo="crear"><i class="bi bi-plus-square"></i> Nueva marca</button></div><?php endif; ?>
        <div class="table-responsive"><table id="tablaMarcas" class="table table-hover tabla-intesis align-middle w-100"><thead><tr><th>Empresa</th><th>Nombre</th><th>Estado</th><th class="text-end">Acciones</th></tr></thead><tbody>
            <?php foreach ($marcas as $marca): ?><tr>
                <td><?= htmlspecialchars($marca['sis_empresa_nombre_comercial']) ?></td>
                <td><?= htmlspecialchars($marca['inv_marca_nombre']) ?></td>
                <td><span class="badge estado-badge estado-<?= strtolower((string) $marca['sis_estado_codigo']) ?>"><?= htmlspecialchars($marca['sis_estado_nombre']) ?></span></td>
                <td class="text-end acciones-tabla">
                    <button type="button" class="btn btn-accion btn-editar-marca" title="Ver marca" data-bs-toggle="modal" data-bs-target="#modalMarca" data-modo="ver" data-id="<?= (int) $marca['inv_marca_id'] ?>" data-empresa="<?= (int) $marca['sis_empresa_id'] ?>" data-nombre="<?= htmlspecialchars($marca['inv_marca_nombre']) ?>"><i class="bi bi-eye"></i></button>
                    <?php if ($permisos['editar']): ?><button type="button" class="btn btn-accion btn-editar-marca" title="Editar marca" data-bs-toggle="modal" data-bs-target="#modalMarca" data-modo="editar" data-id="<?= (int) $marca['inv_marca_id'] ?>" data-empresa="<?= (int) $marca['sis_empresa_id'] ?>" data-nombre="<?= htmlspecialchars($marca['inv_marca_nombre']) ?>"><i class="bi bi-pencil-square"></i></button><?php endif; ?>
                    <?php if ($marca['sis_estado_codigo'] !== 'ACTIVO' && $permisos['activar']): ?><form action="<?= $appUrl ?>/inventario/marcas/activar" method="post" class="d-inline"><input type="hidden" name="marca_id" value="<?= (int) $marca['inv_marca_id'] ?>"><button class="btn btn-accion btn-activar" type="submit" title="Activar marca"><i class="bi bi-toggle-on"></i></button></form><?php endif; ?>
                    <?php if ($marca['sis_estado_codigo'] === 'ACTIVO' && $permisos['inactivar']): ?><form action="<?= $appUrl ?>/inventario/marcas/inactivar" method="post" class="d-inline formulario-confirmar" data-codigo-mensaje="CONFIRMAR_INACTIVAR_MARCA"><input type="hidden" name="marca_id" value="<?= (int) $marca['inv_marca_id'] ?>"><button class="btn btn-accion btn-inactivar" type="submit" title="Inactivar marca"><i class="bi bi-toggle-off"></i></button></form><?php endif; ?>
                </td>
            </tr><?php endforeach; ?>
        </tbody></table></div>
    </section></div></div></main>
</div>
<div class="modal fade modal-intesis" id="modalMarca" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-md modal-dialog-centered"><form class="modal-content" id="formularioMarca" method="post" action="<?= $appUrl ?>/inventario/marcas/crear"><input type="hidden" name="marca_id" id="marca_id"><div class="modal-header"><div><p class="modal-etiqueta">Inventario</p><h2 class="modal-title" id="modalMarcaTitulo">Nueva marca</h2></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body formulario-compacto"><div class="row g-2"><?php if ($esSuperusuario): ?><div class="col-12"><label class="form-label" for="marca_empresa_id">Empresa</label><select class="form-control form-control-sm" id="marca_empresa_id" name="empresa_id" required><option value="">Seleccione</option><?php foreach ($empresas as $empresa): ?><option value="<?= (int) $empresa['sis_empresa_id'] ?>"><?= htmlspecialchars($empresa['sis_empresa_nombre_comercial']) ?></option><?php endforeach; ?></select></div><?php endif; ?><div class="col-12"><label class="form-label" for="marca_nombre">Nombre</label><input class="form-control form-control-sm" id="marca_nombre" name="nombre" maxlength="120" required></div></div></div><div class="modal-footer"><button type="button" class="btn btn-secundario" data-bs-dismiss="modal"><i class="bi bi-x-lg"></i> Cancelar</button><button type="submit" class="btn btn-intesis" id="btnGuardarMarca"><i class="bi bi-save2"></i> Guardar</button></div></form></div></div>
<?php if (!empty($mensaje)): ?><script>window.INTESIS_MENSAJE = <?= json_encode($mensaje, JSON_UNESCAPED_UNICODE) ?>;</script><?php endif; ?>
<script>window.INTESIS_MENSAJES = <?= json_encode($mensajesSistema ?? [], JSON_UNESCAPED_UNICODE) ?>;</script>
<?php require $configuracion->raiz() . '/src/Vistas/plantillas/pie.php'; ?>
